
ARDUINO_LIBS = bitlash gainspan js0n lwm pinoccio

BOARD_TAG = Pinoccio
MCU = atmega1280

BOOTLOADER_PARENT = /Users/vng/OyoroiPinoccio/hardware/pinoccio/avr/bootloaders
BOARDS_TXT = /Users/vng/OyoroiPinoccio/hardware/pinoccio/avr/boards.txt
ARDUINO_VAR_PATH = /Users/vng/OyoroiPinoccio/hardware/pinoccio/avr/variants

include $(ARDMK_DIR)/Arduino.mk

